// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(GaleriContext))]
    partial class GaleriContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Models.Araba", b =>
                {
                    b.Property<int>("ArabaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ARABA_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArabaID"), 1L, 1);

                    b.Property<double>("Fiyat")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("FIYAT");

                    b.Property<int?>("MarkaID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MARKA_ID");

                    b.Property<int?>("ModelID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODEL_ID");

                    b.Property<string>("Plaka")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLAKA");

                    b.Property<string>("Resim")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("RESIM");

                    b.HasKey("ArabaID");

                    b.HasIndex("MarkaID");

                    b.HasIndex("ModelID");

                    b.ToTable("ARABALAR", (string)null);
                });

            modelBuilder.Entity("Models.Marka", b =>
                {
                    b.Property<int>("MarkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MARKA_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarkaID"), 10L, 1);

                    b.Property<string>("MarkaAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MARKA_ADI");

                    b.HasKey("MarkaID");

                    b.ToTable("MARKALAR", (string)null);

                    b.HasData(
                        new
                        {
                            MarkaID = 1,
                            MarkaAdi = "Ferrari"
                        },
                        new
                        {
                            MarkaID = 2,
                            MarkaAdi = "Volswagen"
                        },
                        new
                        {
                            MarkaID = 3,
                            MarkaAdi = "TOFAS"
                        });
                });

            modelBuilder.Entity("Models.Model", b =>
                {
                    b.Property<int>("ModelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODEL_ID");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModelID"), 10L, 1);

                    b.Property<int?>("MarkaID")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MARKA_ID");

                    b.Property<string>("ModelAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("MODEL_ADI");

                    b.Property<int>("ModelYili")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("MODEL_YILI");

                    b.HasKey("ModelID");

                    b.HasIndex("MarkaID");

                    b.ToTable("MODELLER", (string)null);

                    b.HasData(
                        new
                        {
                            ModelID = 1,
                            MarkaID = 1,
                            ModelAdi = "Enzo",
                            ModelYili = 2010
                        },
                        new
                        {
                            ModelID = 2,
                            MarkaID = 1,
                            ModelAdi = "California",
                            ModelYili = 2016
                        },
                        new
                        {
                            ModelID = 3,
                            MarkaID = 2,
                            ModelAdi = "Golf",
                            ModelYili = 2010
                        },
                        new
                        {
                            ModelID = 4,
                            MarkaID = 2,
                            ModelAdi = "Tiguan",
                            ModelYili = 2018
                        },
                        new
                        {
                            ModelID = 5,
                            MarkaID = 3,
                            ModelAdi = "Kartal",
                            ModelYili = 2000
                        },
                        new
                        {
                            ModelID = 6,
                            MarkaID = 3,
                            ModelAdi = "Dogan",
                            ModelYili = 1999
                        },
                        new
                        {
                            ModelID = 7,
                            MarkaID = 3,
                            ModelAdi = "Serce",
                            ModelYili = 1985
                        });
                });

            modelBuilder.Entity("Models.Araba", b =>
                {
                    b.HasOne("Models.Marka", "Marka")
                        .WithMany("Arabalar")
                        .HasForeignKey("MarkaID");

                    b.HasOne("Models.Model", "Model")
                        .WithMany("Arabalar")
                        .HasForeignKey("ModelID");

                    b.Navigation("Marka");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("Models.Model", b =>
                {
                    b.HasOne("Models.Marka", "Marka")
                        .WithMany("Modeller")
                        .HasForeignKey("MarkaID");

                    b.Navigation("Marka");
                });

            modelBuilder.Entity("Models.Marka", b =>
                {
                    b.Navigation("Arabalar");

                    b.Navigation("Modeller");
                });

            modelBuilder.Entity("Models.Model", b =>
                {
                    b.Navigation("Arabalar");
                });
#pragma warning restore 612, 618
        }
    }
}
